# Database connection, Spring Boot JDBC Configuration
#1st line tells spring where the DB is
spring.datasource.url=jdbc:postgresql://localhost:5432/casearch
spring.datasource.username=postgres
spring.datasource.password=Sai#4125
#Spring JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate - Spring Data JPA related
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect