# Database connection, Spring Boot JDBC Configuration
#1st line tells spring where the DB is
#spring.datasource.url=jdbc:postgresql://localhost:5432/casearch
#spring.datasource.username=postgres
#spring.datasource.password=Sai#4125

spring.datasource.primary-db.jdbc-url=jdbc:postgresql://localhost:5432/casearch
spring.datasource.primary-db.username=postgres
spring.datasource.primary-db.password=${DB1_PASSWORD}

spring.datasource.archival-db.jdbc-url=jdbc:postgresql://localhost:5432/archivaldb
spring.datasource.archival-db.username=postgres
spring.datasource.archival-db.password=${DB2_PASSWORD}



#Spring JDBC Driver
spring.datasource.primary-db.driver-class-name=org.postgresql.Driver

spring.datasource.archival-db.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false

# JPA / Hibernate - Spring Data JPA related
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect